name: Docker Cross-Platform Test

on: 
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  docker-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, mcr.microsoft.com/windows/nanoserver:ltsc2022]
        exclude:
          - os: ubuntu-latest
            image: mcr.microsoft.com/windows/nanoserver:ltsc2022
          - os: windows-latest
            image: hello-world
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Docker image
      run: docker run --rm ${{ matrix.image }}
      
    - name: Verify Docker functionality
      run: docker ps -a