name: Workflow Demo

on: 
  workflow_dispatch: 
    
  # schedule:
  #   - cron: "*/1 * * * *"

env:
  ACCESS_ID: ${{ secrets.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
