name: Workflow Demo

on: 
  push:
  workflow_dispatch: 

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - name: echo
      run: docker info

    - name: run image on ${{matrix.os}}
      run: docker run ${{matrix.images}}
